import Todo from '../models/todo';
import Todos from '../models/todos';
import {expect} from '@jest/globals';

test('Todos behave correctly', () => {
  const todo1 = new Todo('1', 'To sleep');
  const todo2 = new Todo('2', 'To awake');
  const updateText: string = 'To eat';
  const falseId: string = '20';
  const todos = new Todos();
  expect(todos).toBeInstanceOf(Todos);
  expect(todos.addTodo(todo1)).toBeGreaterThanOrEqual(0);
  expect(todos.addTodo(todo2)).toBeGreaterThanOrEqual(0);
  expect(todos.getAll).toEqual([todo1, todo2]);
  const worksFind = todos.findTodoById(todo2.id);
  const notWorksFind = todos.findTodoById('3');
  expect(worksFind).toEqual(todo2);
  expect(notWorksFind).toBeUndefined();
  const worksUpdate = todos.updateTodo(todo2.id, updateText);
  const notWorksUpdate = todos.updateTodo(falseId, updateText);
  expect(todos.findTodoById(todo2.id)).toEqual(new Todo(todo2.id, updateText));
  expect(worksUpdate).toBeGreaterThanOrEqual(0);
  expect(notWorksUpdate).toBeLessThan(0);
  const worksDelete = todos.deleteTodoById(todo2.id);
  const notWorksDelete = todos.deleteTodoById(falseId);
  expect(worksDelete).toBeGreaterThanOrEqual(0);
  expect(notWorksDelete).toBeLessThan(0);
  todos.deleteTodoById(todo2.id);
  expect(todos.getAll).toEqual([todo1]);
});